service: localstack-lambda
frameworkVersion: '2.15'

provider:
  name: aws
  runtime: nodejs12.x
  role: arn:aws:iam::407825239838:role/iot_to_lambda

functions:
  hello:
    handler: handler.hello
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - queueEranTester2
              - Arn
      - http:
          path: test
          method: get
resources:
  Resources:
    queueEranTester2:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "queueEranTester2"
    ExampleQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: example-queue
    ExampleUser:
      Type: "AWS::IAM::User"
      Properties:
        UserName: example-user
        Policies:
          - PolicyName: ExampleUserSQSPolicy
            PolicyDocument:
              Version: '2017'
              Statement:
                - Effect: "Allow"
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - {"Fn::Join": [":", ["arn:aws:sqs:*", {"Ref": "AWS::AccountId"}, "example-queue"]]}
    ExampleUserKey:
      Type: AWS::IAM::AccessKey
      Properties:
        UserName:
          Ref: ExampleUser
  Outputs:
    ExampleUserKey:
      Value:
        Ref: ExampleUserKey
    ExampleUserSecret:
      Value: {"Fn::GetAtt": ["ExampleUserKey", "SecretAccessKey"]}
    ExampleStaticValue:
      Value: example-static-value

plugins:
  - serverless-localstack
  - serverless-stack-output

custom:
  output:
    handler: scripts/output.handler # Same syntax as you already know
    file: .build/stack.json # toml, yaml, yml, and json format is available
  localstack:
    debug: true
    stages:
      - local
      - dev
    endpointFile: localstack_endpoints.json
