version: 2.1
orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@0.5.19
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - node/install:
          node-version: "14.16.1"
      # - aws-cli/setup:
      #     profile-name: vn
      - docker/install-docker
      - run: ./.circleci/test.sh

workflows:
  build:
    jobs:
      - build:
          context: base-context